version: "3.4"

services:
  nginx-fpm:
    build: .
    image: dynamedia/docker-nginx-fpm:v1.19.8_7.4.14
    environment:
      - USER_NAME=www-data
      - GROUP_NAME=www-data
      - USER_UID=1000
      - GROUP_GID=1000
    restart: always
    ports:
      - 80:80
    # Get a geoIP2/GeoLite2 database file and name it geoip.mmdb - place it in this directory and uncomment below
    #volumes:
    #  - ./geoip.mmdb/:/etc/nginx/geoip.mmdb
